### ISSUE TITLE
Could you add bcrypt to the Image?

### ISSUE THREAD

**Issue by negue** [hach-que-docker/phabricator#10]
This is what I get in Edit Authentication Provider (Username/password)

```
Algorithm	| Name	| Strength	| Installed	| Install Instructions
bcrypt	| bcrypt | Good	| Not Installed	| Upgrade to PHP 5.5.0 or newer.
```

**Comment by hach-que** [comment]
The next chance I'll get to this will be next week.  Feel free to submit a PR in the mean time (it should just be a case of installing another php5 package).

**Comment by cguentherTUChemnitz** [comment]
I think this ticket is already resolved.
