### ISSUE TITLE
Reduce layers of docker image

### ISSUE THREAD

**Issue by sascha-egerer** [hach-que-docker/phabricator#17]
Each command in the Dockerfile creates a filesystem layer. 
The current Dockerfile has too much commands that can be reduced a lot. 
For example prevent adding files each by one but put them in a folder and add the whol folder instead.
Also the installation of software should be done in as less steps as possible and cleanup must run in the same command.

Do you agree? Should i prepare a PR?

**Comment by hach-que** [comment]
I used to have all the files added in one command, and run a script for the setup in another (for other kinds of older Docker images).  I found that it just made development iteration much slower when working on things, so I decided to drop that.

Given there's only a one-time cost for downloading the image and then you can use it perpetually forever, I don't think there's much value in changing this.
