### ISSUE TITLE
How to forward SSH

### ISSUE THREAD

**Issue by bweston92** [hach-que-docker/phabricator#19]
I can't expose port 22 (sshd conflicts) so how can I redirect a certain ssh user to the phabricator container?

**Comment by hach-que** [comment]
Just change your docker port mappings to map port 22 of the container onto
a different host port.

**Comment by bweston92** [comment]
The Git URI would look weird but should be ok for now.

**Comment by hach-que** [comment]
There's no other way to do it - forwarding SSH for one user is outside the support scope of this project.  I expect that users of this Docker container are mapping the SSH port from the container to port 22 or are mapping it to another port with the awareness that the URL will have a port specification in it.
