### ISSUE TITLE
do not use sshd in docker container

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [hach-que-docker/phabricator#21]
If i see it right, the ssh port 22 is mapped to 24 to provide ssh access to the container. Using sshd inside docker containers is widely discussed as an antipattern. If you just want to access the containers shell you should access it by ssh to your docker's host and run `docker exec -it phabricator_container_name /bin/bash`. That will start the /bin/bash shell of your running container instance. Other tasks like backups is more detailed discussed here:
https://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/

best,
Christian

**Comment by hach-que** [comment]
The new image that's a work in progress (on the newconf branch) removes the
SSH on port 24.

**Comment by hach-que** [comment]
The new image no longer ships an administrative SSHD on port 24 (it still does ship SSHD on port 22 for repository access).
