### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [hach-que-docker/phabricator#22]
The current version seem to crash on startup with the following output:
```
+ sudo -u git ./bin/config set storage.default-namespace phabricator
[2016-05-04 21:53:20] EXCEPTION: (FilesystemException) Requested path '/srv/phabricator/phabricator/conf/local/local.json' is not writable. at [<phutil>/src/filesystem/Filesystem.php:1081]
arcanist(head=master, ref.master=c58f1b9a2507), phabricator(head=master, ref.master=d85386488bf5), phutil(head=master, ref.master=0709cd5cfc26)
  #0 Filesystem::assertWritable(string) called at [<phutil>/src/filesystem/Filesystem.php:69]
  #1 Filesystem::assertWritableFile(string) called at [<phutil>/src/filesystem/Filesystem.php:89]
  #2 Filesystem::writeFile(string, string) called at [<phabricator>/src/infrastructure/env/PhabricatorConfigLocalSource.php:41]
  #3 PhabricatorConfigLocalSource::saveConfig() called at [<phabricator>/src/infrastructure/env/PhabricatorConfigLocalSource.php:12]
  #4 PhabricatorConfigLocalSource::setKeys(array) called at [<phabricator>/src/applications/config/management/PhabricatorConfigManagementSetWorkflow.php:165]
  #5 PhabricatorConfigManagementSetWorkflow::execute(PhutilArgumentParser) called at [<phutil>/src/parser/argument/PhutilArgumentParser.php:410]
  #6 PhutilArgumentParser::parseWorkflowsFull(array) called at [<phutil>/src/parser/argument/PhutilArgumentParser.php:303]
  #7 PhutilArgumentParser::parseWorkflows(array) called at [<phabricator>/scripts/setup/manage_config.php:21]
[ FAILED ] /etc/init.simple/10-boot-conf

```

The file /srv/phabricator/phabricator/conf/local/local.json exists, but is not writable. When i change it to 755 access right, than it runs fine. But i don't want to because it is insecure. It seems to me that the file is owned by the wrong user, because it is owned by root.

My statement, used to run the container is:
`docker run --link mariadb101-phabricator:sqlDB --volume /docker/phabricator/config:/config hachque/phabricator:latest`

**Comment by hach-que** [comment]
That's... odd. I certainly don't get that on start up in my system.

I'm assuming from that Docker command line you're using the legacy way of configuring Phabricator (which is still supported). Do you change the permissions of that file anywhere inside your start up scripts away from the default?

Is it possible for you to post the configuration scripts here (remove all sensitive credentials)?

**Comment by cguentherTUChemnitz** [comment]
Sorry for the harassment. It was my fault. I did not move my config from the .pre file to the environment variables. So i had the config folder still mounted as volume, which introduces this problem.
