### ISSUE TITLE
Missing entry in full environment variable list

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [hach-que-docker/phabricator#24]
Hi,

the env var `PHABRICATOR_REPOSITORY_STORAGE` is defined in the basic [readme](https://github.com/hach-que-docker/phabricator/blob/master/README.md) wiki site, but is not mentioned in the [full environment variable list](https://github.com/hach-que-docker/phabricator/blob/master/ENV-LIST.md)

**Comment by hach-que** [comment]
Thanks, the README was supposed to say `PHABRICATOR_REPOSITORY_PATH` not PHABRICATOR_REPOSITORY_STORAGE`.
