### ISSUE TITLE
Volume for local config

### ISSUE THREAD

**Issue by pschiffe** [hach-que-docker/phabricator#25]
Hello,

when using Phabricator, I found out, that some [config options are not stored in DB](https://secure.phabricator.com/book/phabricator/article/configuration_locked/) (phpmailer for example). To configure those options, one must use the `bin/config` utility, which stores configuration in the `/srv/phabricator/phabricator/conf/local` folder. I think that it would be helpful, if you could document to use volume for that folder, otherwise the config will be lost between the upgrades.

Thanks.

peter

**Comment by hach-que** [comment]
We don't expect data to be kept between starting and stopping the Phabricator image, nor between upgrades.  All of the environment variables and configuration mechanisms we use are specifically designed so you can throw away the instance of the image after each run and start it fresh.

Your configuration mechanism (whether it's using a /config mapping with startup scripts in it, or whether you're using environment variables or baking) should not require storing data inside the Phabricator configuration directory between runs.

**Comment by pschiffe** [comment]
Thanks for the reply. I'm using env vars for config, and to configure mailer I should bake my own image - understand now.

**Comment by hach-que** [comment]
You don't need to bake your own image.  You can volume mount a directory with custom startup scripts (which can call `bin/config`) and tell the Phabricator image to run them using environment variables.

See this link: https://github.com/hach-que-docker/phabricator/blob/master/ADVANCED-CONFIG.md#running-custom-commands-during-the-boot-process

**Comment by pschiffe** [comment]
Awesome! Thank you. I somehow didn't put it together, from the description of that feature, that I can also use that for the configuration of Phabricator itself, not just to add custom extension, modify MYSQL connection or so..
