### ISSUE TITLE
How to ssh into running container as root user?

### ISSUE THREAD

**Issue by sanketgajjar** [hach-que-docker/phabricator#3]
Running the container using below command : 

/usr/bin/docker run -p 80:80 -p 2222:22 -p 843:843 -p 22280:22280 -v /home/sanket/hachque/config:/config -v /home/sanket/hachque/repo-storage:/srv/repo --name=phabricator --link mariadb:linked_mariadb hachque/phabricator

**Comment by utrack** [comment]
Now you can use `docker exec -it <container> bash`, btw.

**Comment by hach-que** [comment]
Yeah I can probably remove the SSH daemon from containers now..

**Comment by hach-que** [comment]
Closing because this issue is resolved.
