### ISSUE TITLE
missing path for git-http-backend

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [hach-que-docker/phabricator#31]
The git repository status shows:

> Missing Binary git-http-backend	Unable to find this binary in the webserver's PATH. You may need to configure environment.append-paths.

The git-http-backend is located in `/usr/lib/git`.

So please add this path also to the existing search pathes. The following entry in the local.json solves the issue:

>   "environment.append-paths": [
>     "/bin",
>     "/usr/bin",
>     "/usr/local/bin",
>     "/usr/lib/git"
>   ],

**Comment by hach-que** [comment]
I'll see if I can find some time this week to address this.
