### ISSUE TITLE
incomplete SSL_TYPE external configuration

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [hach-que-docker/phabricator#33]
Hi there,

i am using a nginx ssl terminating reverse proxy. The basic setup runs fine with the SSL_TYPE external configuration. But one point is missing. The client browser does not know that he should connect with https websocket connection to the notification server. The last missing point was the
```
<?php

$_SERVER['HTTPS'] = true;
```
in the /srv/phabricator/phabricator/support/preamble.php

After that, the notifications run fine in combination with the ssl terminating nginx reverse proxy following the official configuration guide:
https://secure.phabricator.com/book/phabricator/article/notifications/

Or like described in my bug report:
https://secure.phabricator.com/T11103

**Comment by hach-que** [comment]
I'll see if I can find some time this week to address this.
