### ISSUE TITLE
Cannot restart docker container

### ISSUE THREAD

**Issue by romeupalos** [hach-que-docker/phabricator#34]
While restarting docker machine an error is returned and the machine keeps rebooting.

> phabricator_search.edge                            OK
> phabricator_search.edgedata                        OK
> phabricator_search.search_document                 OK
> phabricator_search.search_documentfield            OK
> phabricator_search.search_documentrelationship     OK
> phabricator_search.search_editengineconfiguration  OK
> phabricator_search.search_editengineconfigurationtransaction OK
> phabricator_search.search_indexversion             OK
> phabricator_search.search_namedquery               OK
> phabricator_search.search_profilepanelconfiguration OK
> phabricator_search.search_profilepanelconfigurationtransaction OK
> phabricator_search.search_savedquery               OK
> + /srv/phabricator/phabricator/bin/storage upgrade --force
> Storage is up to date. Use 'storage status' for details.
> Verifying database schemata...
> Found no adjustments for schemata.
> + '[' '' '!=' '' ']'
> [ STARTING ] /etc/init.simple/15-https
> mkdir: cannot create directory '/etc/nginx/servers': File exists
> mv: cannot stat '/etc/nginx/disabled-server-http.conf': No such file or directory
> chmod: cannot access '/etc/nginx.key': No such file or directory
> mv: cannot stat '/etc/nginx/disabled-server-https-manual.conf': No such file or directory
> [ FAILED ] /etc/init.simple/15-https
>

**Comment by hach-que** [comment]
This image is intended to be thrown away after one use; that is, you should run it with `docker run --rm ...`.  Are you trying to restart an existing container?

**Comment by romeupalos** [comment]
I'm sorry. I was trying to reuse the container. I ran it with --restart=always. In case of failure it was being restarted. But I'll change to throw away after the use! Thanks!
