### ISSUE TITLE
apcu PHP extension not available

### ISSUE THREAD

**Issue by romeupalos** [hach-que-docker/phabricator#35]
Could you please bake into the image the apcu PHP extension?

From phabricator setup issues screen:

> Installing the "APCu" PHP extension will improve performance. This extension is strongly recommended. Without it, Phabricator must rely on a very inefficient disk-based cache.

**Comment by hach-que** [comment]
The image does have the APCu extension, but you need to explicitly enable it with `--env ENABLE_ACPU=true`.

If that doesn't work, feel free to re-open / open another task.

**Comment by CGamesPlay** [comment]
I'm confused, because setting this option doesn't seem to have any effect (the warning is still there) and because ENABLE_APCU doesn't occur in this repository. Are you sure this is live?

**Comment by CGamesPlay** [comment]
Ignore me. I was typing "ACPU" instead of "APCU". Whoops >_<

**Comment by dlgiang** [comment]
@hach-que  Can you please edit your comment `--env ENABLE_ACPU=true.`
I read it and have to fix it to `--env ENABLE_APCU=true.`
Hope no any other will get same issue
