### ISSUE TITLE
SVN hosting and missing locales 

### ISSUE THREAD

**Issue by alex3d** [hach-que-docker/phabricator#37]
Hosted SVN repo doesn't work because of missing locales:
```
$ svn checkout ...
phabricator-ssh-exec: Unexpected output to stderr on exec channel: svnserve: warning: cannot set LC_CTYPE locale
svnserve: warning: environment variable LANG is en_US.UTF-8
svnserve: warning: please check that your locale name is correct
```

`zypper in glibc-locale` solves this problem.

**Comment by hach-que** [comment]
I've just updated the list of packages to install with glibc-locale; in an hour or two the Docker hub should have finished preparing a new image on `latest`.

If you could try that out and verify that the issue is fixed, then I can close this issue.

**Comment by alex3d** [comment]
Problem solved
