### ISSUE TITLE
Site not found for Phab but my test PHP file works.

### ISSUE THREAD

**Issue by rung2kf** [hach-que-docker/phabricator#38]
Hi,
I'm new to Phabricator & nginx; however, I believe I have set up everything correctly and am able to successfully test a PHP page w/ mySQL connection running your Docker image. Test file works at 'phabricator.somecompany.com:8088/phptest.php'.

mySQL connection is working for this container as well.  What I don't understand is why do I keep getting 'site not found' when I navigate to 'phabricator.somecompany.com:8088'.  The following are the logs and configurations that I used.  Any help is greatly appreciated.

**To build image:**  
`docker build -t hachque/phabricator .`

**To run image:**
`./run.sh
`

**Contents of run.sh:**
```
docker run \
    --name=hphab\
    --rm -p 8088:80 -p 443:443 -p 8022:22 \
    --env PHABRICATOR_HOST=somecompany.com \
    --env PHABRICATOR_URI=phabricator.somecompany.com \
    --link phab_test:mysql \
    --env MYSQL_LINKED_CONTAINER=MYSQL \
    --env MYSQL_PORT=3306 \
    --env MYSQL_USER=phab \
    --env MYSQL_PASS='mysqlpassword' \
    --env PHABRICATOR_REPOSITORY_PATH='/repos' \
    -v ${HOME}/myRepos/phab_repo:/repos \
    hachque/phabricator 
```
Attached log file for container run:
[hphab_run.txt](https://github.com/hach-que-docker/phabricator/files/354820/hphab_run.txt)

Running containers:  phab_test contains mySQL server.
```
### MacBook-Pro.local:.../~[10:45:22]$ docker ps
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS                                                                      NAMES
7be8187813a4        hachque/phabricator   "/init"                32 hours ago        Up 32 hours         24/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8022->22/tcp, 0.0.0.0:8088->80/tcp   hphab
0a2846df95c6        oi/testphab           "/root/cont_init.sh"   12 days ago         Up 12 days          0.0.0.0:3306->3306/tcp, 0.0.0.0:8080->80/tcp                               phab_test
```

**Comment by hach-que** [comment]
Looks like this page: https://github.com/hach-que-docker/phabricator/blob/master/BASIC-CONFIG.md has a mistake in it.

It should just be `PHABRICATOR_HOST=phabricator.somecompany.com`.  `PHABRICATOR_URI` isn't an actual setting.

**Comment by hach-que** [comment]
I've just corrected the documentation.  I'll wait for confirmation that changing it to `PHABRICATOR_HOST` fixes it before closing this issue.

**Comment by rung2kf** [comment]
That fixed it!  Thank you!
However, I got another issue which looks to be a redirection issue.  Since I mapped the internal port 80 to the external port 8088, I got a 'page not found' with a URL of 'http://phabricator.somecompany.com/auth/register/'.
When I remapped port 80 to 80, it worked and I got Phabricator's admin setup page.  I'll ask this question in another post.
