### ISSUE TITLE
"gzinflate() is not available; unable to read deflated data!"

### ISSUE THREAD

**Issue by franc0is** [hach-que-docker/phabricator#4]
It looks like some dependency is missing, I'm trying to wrangle which. I installed this container today and ported my data over from an old phabricator install, but every differential diff flashes the same error:
Screenshot: https://www.dropbox.com/s/vf86m8wq284f5q1/Screenshot%202014-12-08%2021.19.19.png?dl=0

I wrote a quick test to check whether or not gzdecode worked properly:
```
<?php

echo phpversion().", ";

if (function_exists("gzdecode")) {
  echo "gzdecode OK, ";
} else {
  echo "gzdecode no OK, ";
}

if (extension_loaded('zlib')) {
  echo "zlib extension loaded\n";
} else {
  echo "zlib extension not loaded\n";
}

?>
```
on my host machine I get: `5.4.33, gzdecode OK, zlib extension loaded`
inside the docker image: `5.4.20, gzdecode no OK, zlib extension not loaded`

**Comment by hach-que** [comment]
This should be fixed with 045985b75e61e7f548bd73a92b452cc19bf5e30e, although I never experienced this issue myself.
