### ISSUE TITLE
Clone from the stable branch of phabricator

### ISSUE THREAD

**Issue by kocsenc** [hach-que-docker/phabricator#46]
When using the `ENABLE_UPDATE_ON_START` flag it always updates to the latest commit on `master` branch.
However, it seems the [phabricator repo](https://github.com/phacility/phabricator) has a `stable` branch.

I think it could be fair to assume that we want to update to the latest stable branch. Or have additional environment variables.

**Comment by hach-que** [comment]
You should be able to clone from the stable branch by setting the following environment variables:

```
OVERRIDE_PHABRICATOR_BRANCH=stable
OVERRIDE_ARCANIST_BRANCH=stable
OVERRIDE_LIBPHUTIL_BRANCH=stable
```

This is outlined in the [Advanced Configuration](https://github.com/hach-que-docker/phabricator/blob/master/ADVANCED-CONFIG.md) document.

Please let me know if that doesn't work.
