### ISSUE TITLE
aphlict config outdated

### ISSUE THREAD

**Issue by ramm** [hach-que-docker/phabricator#6]
it seems like phabricator guys changed the way aphlict (notifications) work some time ago.

```
[ STARTING ] /etc/init.simple/40-aphlict
/srv/phabricator/phabricator /
Usage Exception: The notification server should not be run as root. It no longer requires access to privileged ports.
/
```

**Comment by hach-que** [comment]
This changed a few days ago and I haven't had a chance to update it.

**Comment by ramm** [comment]
Do we need anything else besides launching it with git user and changing readme for the new port?

**Comment by hach-que** [comment]
I haven't checked the new docs, but you could try get it working by
launching Aphlict with script.post and then submitting a PR once the new
command works.
