### ISSUE TITLE
git ssh access freeze

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [hach-que-docker/phabricator#61]
Accessing my git repos with git ssh freezes up the connection. After some time the commands are executed correctly. This is related to the problem that the sshd of the phabricator does an rever dns lookup for the connecting client, but the ip does not own a rdns entry. So the phabricator waits for an dns timeout.

To solve this, the DNS lookup can be deactivated for the sshd. I filed a PR for this:
https://github.com/hach-que-docker/phabricator/pull/60

**Comment by hach-que** [comment]
The fix for this is merged now.
