### ISSUE TITLE
Unable to push to repo after recent update

### ISSUE THREAD

**Issue by Matan** [hach-que-docker/phabricator#62]
Hi,

Sorry for the cross linking of issues. I assumed I would need to go directly to Phabrictor to get assistance on an issue like this.

Please see the details here: https://secure.phabricator.com/T11947

I've been using this docker for a while now and it's been working great for my company.

Any help would be greatly appreciated.

Thanks!

**Comment by Matan** [comment]
The issue has been identified! Git 2.11 is to blame. Downgrading git in my custom entrypoint solves the problem.

```
## Manually install specific version of git
zypper --non-interactive install wget

GIT_VERISON=2.10.2
wget https://github.com/git/git/archive/v$GIT_VERISON.tar.gz
tar -zxf v$GIT_VERISON.tar.gz

cd git-$GIT_VERISON

# https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
make configure
./configure --prefix=/usr
make all doc info
make install install-doc install-html install-info

cd ..
```

**Comment by hach-que** [comment]
Yeah, upstream support is pretty much limited to their hosted solution these days.

I'll see if I can find a software repository which has Git as 2.10.2 instead of 2.11.

**Comment by hach-que** [comment]
(Reopening to track Git versioning issue)

**Comment by hach-que** [comment]
Thanks for reporting this issue.
