### ISSUE TITLE
Waiting for /run/sshd.pid to appear...

### ISSUE THREAD

**Issue by ostraaten** [hach-que-docker/phabricator#7]
On my Vagrant box when I run something like

```bash
docker run -p 2222:22 -p 22280:22280 -p 80:80 -p 443:443 -v /vagrant/dockers/hach-que-docker-phabricator/config:/config -v /tmp/repo/storage:/srv/repo --name=phabricator hachque/phabricator
```

After some time, every second or so there is a message

```bash
Waiting for /run/sshd.pid to appear...
Waiting for /run/sshd.pid to appear...
Waiting for /run/sshd.pid to appear...
Waiting for /run/sshd.pid to appear...
Waiting for /run/sshd.pid to appear...
Waiting for /run/sshd.pid to appear...
```

Any idea what is causing this? Can I ignore this?

Does the script assume there is no ssh on host?

**Comment by hach-que** [comment]
SSH runs inside the Docker instance, so Phabricator can provide repository hosting over SSH.  Is there already an SSH daemon listening on port 22 on the host or something?

**Comment by hach-que** [comment]
Closing this as there has been no response.
