### ISSUE TITLE
phab hosted git repos - can't read/write over ssh

### ISSUE THREAD

**Issue by sheershoff** [hach-que-docker/phabricator#9]
After #8 the repos are created. I've added my public key to my phabricator account. But I neither can  push to nor pull from it.

```
sheershoff@sheershoff-v5kbnt:~/projects/robowalker/robowalker$ git clone ssh://phab.mydomain.ru/diffusion/RW/robowalker.git
Cloning into 'robowalker'...
Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I tried setting `log.ssh.path` to `/var/www/phab.ssh.log`, but the file doesn't appear inside the instance. Also I tried to find some logs for that inside instance or upstart logs where the output of docker command is gathered, and failed to find anything on this issue. Also tried to set diffusion.ssh-(user|host|port) to (git|phab.mydomain.ru|22) and this didn't help either. Any ideas what should I check?

The command that runs phabricator: `/usr/bin/docker run --rm -p 22:22 -p 22280:22280 -p 80:80 -p 443:443 -v /var/www/web/phabricator/phabricator/config:/config -v /var/www/web/phabricator/repo:/var/repo --link mariadb:linked_mariadb --name=phabricator hachque/phabricator`

**Comment by hach-que** [comment]
This image is based on OpenSUSE with a custom lightweight init system; there won't be any upstart logs. You should try and SSH to the Docker instance on port 24 and find out where the SSH logs are configured to go (I'd expect it to be under /var/log). You might also want to check /var/log/auth.log to see if that exists. 

I don't know why you'd be having this issue though, unless you've customized the image or Phabricator, or if you have some kind of audit system enabled in the host kernel.

**Comment by sheershoff** [comment]
Just noticed that the repository URL in one instance of phabricator was missing the `git@` part, and in another one it is present.

I've added the `git@` to the remote urls and git pull/push now works like a charm.
